name: declarative_navigator
description: "Fully declarative, state-driven routing for Flutter's Navigator 2.0. Makes routing as simple as widgets!"
version: 0.0.2
repository: https://github.com/LunaONE/declarative_navigator

environment:
  sdk: ">=3.2.3 <4.0.0"
  flutter: ">=3.16.3"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:

topics:
  - routing
  - deep-linking
  - navigation
